export const ROUTES = {
  Home: "/",
  Register: "/register",
  Login: "/login",
  Profile: "/profile",
  GenerateSentences: "/generate-sentences",
  GoogleAuthSuccess: "/auth/success",
  Welcome: "/welcome",
  VerifyEmail: "/auth/verify-email",
  PasswordRecovery: "/passwordRecovery",
  ResetPassword: "/auth/reset-password",
  AdminPanel: "/adminPanel",
  TwoFactorVerify: "/auth/2fa-verify",
  SavedSentences: "/saved-sentences",
} as const;
