export const ROUTES = {
  Home: "/",
  Register: "/register",
  Login: "/login",
  Profile: "/profile",
  GenerateSentences: "/generate-sentences",
  GoogleAuthSuccess: "/auth/success",
  Welcome: "/welcome",
  VerifyEmail: "/auth/verify-email",
  PasswordRecovery: "/passwordRecovery",
  ResetPassword: "/auth/reset-password",
  AdminPanel: "/adminPanel",
  TwoFactorVerify: "/auth/2fa-verify",
  SavedSentences: "/saved-sentences",
  TranslateWord: "/translate-word",
  TranslateText: "/translate-text",
  SavedWords: "/saved-words",
  VocabularyQuiz: "/vocabulary-quiz",
  Tenses: "/tenses",
  TenseDetail: "/tenses/:tenseId",
  TensesQuiz: "/tenses-quiz",
  TensePractice: "/tense-practice",
} as const;
